# Hate_speech-Advance Text Processing


# Problem Statement
To preprocess dataset for future use of supervised and unsupervised learning

# 1)- Importing key modules

In [1]:
# Let's be rebels and ignore warnings for now
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Visualization 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
import nltk
import pandas as pd
import numpy as np
import requests
import pickle

# 2)-Loading Dataset

In [4]:
train = pd.read_pickle('basic_text_pre-process.pkl')
train.head()

id  label                                              tweet  word_count  \
0   1      0  father dysfunctional selfish drag kid dysfunct...          21   
1   2      0  thanks lyft credit cant use cause dont offer w...          22   
2   3      0                                     bihday majesty           5   
3   4      0                            model take urð ðððð ððð          17   
4   5      0                      factsguide society motivation           8   

   char_count  avg_word  stopwords  hastags  numerics  upper  
0         102  4.555556         10        1         0      0  
1         122  5.315789          5        3         0      0  
2          21  5.666667          1        0         0      0  
3          86  4.928571          5        1         0      0  
4          39  8.000000          1        1         0      0

# 3)-Advance Text Processing
- N-grams
- Term Frequency
- Inverse Document Frequency
- Term Frequency-Inverse Document Frequency (TF-IDF)
- Bag of Words
- Sentiment Analysis
- Word Embedding

### 3.1)-N-gram
N-grams are the combination of multiple words used together. Ngrams with N=1 are called unigrams. Similarly, bigrams (N=2), trigrams (N=3) and so on can also be used.

Unigrams do not usually contain as much information as compared to bigrams and trigrams. The basic principle behind n-grams is that they capture the language structure, like what letter or word is likely to follow the given one. The longer the n-gram (the higher the n), the more context you have to work with. Optimum length really depends on the application – if your n-grams are too short, you may fail to capture important differences. On the other hand, if they are too long, you may fail to capture the “general knowledge” and only stick to particular cases.

In [5]:
train['tweet'][0]

'father dysfunctional selfish drag kid dysfunction run'

In [6]:
from textblob import TextBlob
TextBlob(train['tweet'][0]).ngrams(2)

[WordList(['father', 'dysfunctional']),
 WordList(['dysfunctional', 'selfish']),
 WordList(['selfish', 'drag']),
 WordList(['drag', 'kid']),
 WordList(['kid', 'dysfunction']),
 WordList(['dysfunction', 'run'])]

### 3.2)-Term frequency
Term frequency is simply the ratio of the count of a word present in a sentence, to the length of the sentence.

Therefore, we can generalize term frequency as:

TF = (Number of times term T appears in the particular row) / (number of terms in that row)

In [7]:
tf1 = (train['tweet'][1:2]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
tf1.columns = ['words','tf']
tf1

words  tf
0           van   1
1         cause   1
2          cant   1
3   disapointed   1
4    getthanked   1
5         offer   1
6           use   1
7          dont   1
8        thanks   1
9        credit   1
10         lyft   1
11          pdx   1
12   wheelchair   1

### 3.3)-Inverse Document Frequency

The intuition behind inverse document frequency (IDF) is that a word is not of much use to us if it’s appearing in all the documents.

Therefore, the IDF of each word is the log of the ratio of the total number of rows to the number of rows in which that word is present.

IDF = log(N/n), where, N is the total number of rows and n is the number of rows in which the word was present.

In [8]:
for i,word in enumerate(tf1['words']):
  tf1.loc[i, 'idf'] = np.log(train.shape[0]/(len(train[train['tweet'].str.contains(word)])))

tf1

words  tf        idf
0           van   1   5.236505
1         cause   1   5.690172
2          cant   1   3.542509
3   disapointed   1  10.372303
4    getthanked   1   9.679156
5         offer   1   6.522155
6           use   1   3.574363
7          dont   1   3.746911
8        thanks   1   4.597751
9        credit   1   7.327781
10         lyft   1   8.762865
11          pdx   1   8.762865
12   wheelchair   1   9.273691

**The more the value of IDF, the more unique is the word.**

### 3.4)-Term Frequency – Inverse Document Frequency (TF-IDF)
TF-IDF is the multiplication of the TF and IDF

In [9]:
tf1['tfidf'] = tf1['tf'] * tf1['idf']
tf1

words  tf        idf      tfidf
0           van   1   5.236505   5.236505
1         cause   1   5.690172   5.690172
2          cant   1   3.542509   3.542509
3   disapointed   1  10.372303  10.372303
4    getthanked   1   9.679156   9.679156
5         offer   1   6.522155   6.522155
6           use   1   3.574363   3.574363
7          dont   1   3.746911   3.746911
8        thanks   1   4.597751   4.597751
9        credit   1   7.327781   7.327781
10         lyft   1   8.762865   8.762865
11          pdx   1   8.762865   8.762865
12   wheelchair   1   9.273691   9.273691

We can see that the TF-IDF has penalized words like ‘don’t’, ‘can’t’, and ‘use’ because they are commonly occurring words. However, it has given a high weight to “disappointed” since that will be very useful in determining the sentiment of the tweet.

In [10]:
# Let's apply to all
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=1000, lowercase=True, analyzer='word', stop_words= 'english',ngram_range=(1,1))
train_vect = tfidf.fit_transform(train['tweet'])

In [11]:
train_vect

<31962x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 113368 stored elements in Compressed Sparse Row format>

In [12]:
# Convert to dense data and also store as document term matrix of tf-idf
tfidf_dtm = pd.DataFrame(train_vect.toarray(), columns=tfidf.get_feature_names())

In [13]:
tfidf_dtm.head()

able  absolutely  account  act  action  actor  actually  adapt  add  adult  \
0   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0    0.0   
1   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0    0.0   
2   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0    0.0   
3   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0    0.0   
4   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0    0.0   

   ...   âï  âïð   ðâ  ðâï   ðð       ððð      ðððð  ððððð  ðððððð   ó¾  
0  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0     0.0  0.0  
1  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0     0.0  0.0  
2  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0     0.0  0.0  
3  ...  0.0  0.0  0.0  0.0  0.0  0.448983  0.496101    0.0     0.0  0.0  
4  ...  0.0  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0     0.0  0.0  

[5 rows x 1000 columns]

In [14]:
#We can always take it to term-document matrix.
tfidf_tdm=tfidf_dtm.transpose()

In [15]:
tfidf_tdm.head()

0      1      2      3      4      5      6      7      8      \
able          0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
absolutely    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
account       0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
act           0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
action        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

            9      ...  31952  31953  31954  31955  31956  31957  31958  \
able          0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
absolutely    0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
account       0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
act           0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
action        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

            31959  31960  31961  
able          0.0    0.0    0.0  
absolutely    0.0    0.0    0.0  
account       0.0    0.0    0.0  
act           0.0    1.0    0.0  
action        0.0    0.0    0.0  

[5 rows x 31962 columns]

### 3.5)-Bag of Words
Bag of Words (BoW) refers to the representation of text which describes the presence of words within the text data. The intuition behind this is that two similar text fields will contain similar kind of words, and will therefore have a similar bag of words. Further, that from the text alone we can learn something about the meaning of the document.

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(max_features=1000, lowercase=True, ngram_range=(1,1),analyzer = "word")
train_bow = bow.fit_transform(train['tweet'])
train_bow

<31962x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 127751 stored elements in Compressed Sparse Row format>

### 3.6)-Sentiment Analysis

In [17]:
#check the sentiment of the first few tweets

train['tweet'][:5].apply(lambda x: TextBlob(x).sentiment)

0    (-0.3, 0.5354166666666667)
1                    (0.2, 0.2)
2                    (0.0, 0.0)
3                    (0.0, 0.0)
4                    (0.0, 0.0)
Name: tweet, dtype: object

it returns a tuple representing polarity and subjectivity of each tweet. Here, we only extract polarity as it indicates the sentiment as value nearer to 1 means a positive sentiment and values nearer to -1 means a negative sentiment

In [18]:
train['sentiment'] = train['tweet'].apply(lambda x: TextBlob(x).sentiment[0] )
train[['tweet','sentiment']].head()

tweet  sentiment
0  father dysfunctional selfish drag kid dysfunct...       -0.3
1  thanks lyft credit cant use cause dont offer w...        0.2
2                                     bihday majesty        0.0
3                            model take urð ðððð ððð        0.0
4                      factsguide society motivation        0.0

### 3.7)-Word Embeddings
Word Embedding is the representation of text in the form of vectors. The underlying idea here is that similar words will have a minimum distance between their vectors.

#### word2vec

Word2Vec models require a lot of text, so either we can train it on our training data or we can use the pre-trained word vectors developed by Google, Wiki, etc.

In [19]:
!pip install -U gensim

Requirement already up-to-date: gensim in /opt/conda/lib/python3.7/site-packages (3.8.2)


In [20]:
# applying glove for word embedding
from gensim.scripts.glove2word2vec import glove2word2vec
''' source: https://nlp.stanford.edu/projects/glove/ '''
glove_input_file = 'glove.6B.100d.txt'
word2vec_output_file = 'glove.6B.100d.txt.word2vec'
glove2word2vec(glove_input_file, word2vec_output_file)

(400000, 100)

In [21]:
from gensim.models import KeyedVectors # load the Stanford GloVe model
filename = 'glove.6B.100d.txt.word2vec'
model = KeyedVectors.load_word2vec_format(filename, binary=False)

Let’s say our tweet contains a text saying ‘go away’. We can easily obtain it’s word vector

In [22]:
model['go']

array([-0.078894,  0.4616  ,  0.57779 , -0.71637 , -0.13121 ,  0.4186  ,
       -0.29156 ,  0.52006 ,  0.089986, -0.35062 ,  0.51755 ,  0.51998 ,
        0.15218 ,  0.41485 , -0.12377 , -0.37222 ,  0.0273  ,  0.75673 ,
       -0.8739  ,  0.58935 ,  0.46662 ,  0.62918 ,  0.092603, -0.012868,
       -0.015169,  0.25567 , -0.43025 , -0.77668 ,  0.71449 , -0.3834  ,
       -0.69638 ,  0.23522 ,  0.11396 ,  0.02778 ,  0.071357,  0.87409 ,
       -0.1281  ,  0.063576,  0.067867, -0.50181 , -0.28523 , -0.072536,
       -0.50738 , -0.6914  , -0.53579 , -0.11361 , -0.38234 , -0.12414 ,
        0.011214, -1.1622  ,  0.037057, -0.18495 ,  0.01416 ,  0.87193 ,
       -0.097309, -2.3565  , -0.14554 ,  0.28275 ,  2.0053  ,  0.23439 ,
       -0.38298 ,  0.69539 , -0.44916 , -0.094157,  0.90527 ,  0.65764 ,
        0.27628 ,  0.30688 , -0.57781 , -0.22987 , -0.083043, -0.57236 ,
       -0.299   , -0.81112 ,  0.039752, -0.05681 , -0.48879 , -0.18091 ,
       -0.28152 , -0.20559 ,  0.4932  , -0.033999, 

In [23]:
model['away']

array([-0.10379 , -0.014792,  0.59933 , -0.51316 , -0.036463,  0.6588  ,
       -0.57906 ,  0.17819 ,  0.23663 , -0.21384 ,  0.55339 ,  0.53597 ,
        0.041444,  0.16095 ,  0.017093, -0.37242 ,  0.017974,  0.39268 ,
       -0.23265 ,  0.1818  ,  0.66405 ,  0.98163 ,  0.42339 ,  0.030581,
        0.35015 ,  0.25519 , -0.71182 , -0.42184 ,  0.13068 , -0.47452 ,
       -0.08175 ,  0.1574  , -0.13262 ,  0.22679 , -0.16885 , -0.11122 ,
       -0.32272 , -0.020978, -0.43345 ,  0.172   , -0.67366 , -0.79052 ,
        0.10556 , -0.4219  , -0.12385 , -0.063486, -0.17843 ,  0.56359 ,
        0.16986 , -0.17804 ,  0.13956 , -0.20169 ,  0.078985,  1.4497  ,
        0.23556 , -2.6014  , -0.5286  , -0.11636 ,  1.7184  ,  0.33254 ,
        0.12136 ,  1.1602  , -0.2914  ,  0.47125 ,  0.41869 ,  0.35271 ,
        0.47869 , -0.042281, -0.18294 ,  0.1796  , -0.24431 , -0.34042 ,
        0.20337 , -0.93676 ,  0.013077,  0.080339, -0.36604 , -0.44005 ,
       -0.35393 ,  0.15907 ,  0.55807 ,  0.1492  , 

We then take the average to represent the string ‘go away’ in the form of vectors having 100 dimensions

In [24]:
(model['go'] + model['away'])/2

array([-0.091342  ,  0.223404  ,  0.58856   , -0.614765  , -0.0838365 ,
        0.5387    , -0.43531   ,  0.349125  ,  0.163308  , -0.28223   ,
        0.53547   ,  0.52797496,  0.096812  ,  0.2879    , -0.0533385 ,
       -0.37232   ,  0.022637  ,  0.574705  , -0.553275  ,  0.385575  ,
        0.565335  ,  0.805405  ,  0.2579965 ,  0.0088565 ,  0.1674905 ,
        0.25543   , -0.571035  , -0.59926   ,  0.422585  , -0.42896   ,
       -0.389065  ,  0.19631   , -0.00933   ,  0.127285  , -0.0487465 ,
        0.381435  , -0.22540998,  0.021299  , -0.1827915 , -0.16490501,
       -0.47944498, -0.431528  , -0.20091   , -0.55665   , -0.32982   ,
       -0.088548  , -0.28038502,  0.219725  ,  0.090537  , -0.67012   ,
        0.0883085 , -0.19332   ,  0.0465725 ,  1.160815  ,  0.0691255 ,
       -2.47895   , -0.33707   ,  0.083195  ,  1.86185   ,  0.283465  ,
       -0.13081   ,  0.927795  , -0.37028   ,  0.1885465 ,  0.66198   ,
        0.505175  ,  0.37748498,  0.1322995 , -0.380375  , -0.02

We have converted the entire string into a vector which can now be used as a feature in any modelling technique.